name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        working-directory: ./SalahTracker
        run: npm install

      - name: Expo Prebuild
        working-directory: ./SalahTracker
        run: npx expo prebuild --platform android --clean --no-interactive

      - name: Make Gradlew Executable
        working-directory: ./SalahTracker/android
        run: chmod +x gradlew

      - name: Build Release APK using Gradle
        working-directory: ./SalahTracker/android
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SalahTracker-Release-APK
          path: SalahTracker/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 14
